/**
 * Shared TypeScript types for Telefun Realistic Mode.
 *
 * These types are used across multiple real-time engines (P0/P1/P2)
 * and post-session evaluation components.
 */

import type { SessionMetrics } from '@/app/types/voiceAssessment';
import type { TelefunSessionState } from '../../types';

// ---------------------------------------------------------------------------
// Core Enums / Union Types
// ---------------------------------------------------------------------------

/**
 * Consumer persona types available for simulation sessions.
 * Each persona has distinct language patterns, emotional intensity ranges,
 * and behavioral characteristics.
 */
export type ConsumerPersonaType =
  | 'angry'
  | 'confused'
  | 'rushed'
  | 'passive'
  | 'critical'
  | 'cooperative';

/**
 * Conversation phases inferred from exchange count and content patterns.
 * Used by Fallback Response Manager, Prolonged Silence Handler, and
 * Disruption Scenario Engine to select contextually appropriate responses.
 */
export type ConversationPhase =
  | 'greeting'
  | 'problem_statement'
  | 'explanation'
  | 'negotiation'
  | 'closing';

/**
 * Categories for classifying short agent responses (< 3s duration).
 * Used by the Short Response Classifier and consumed by the
 * Prolonged Silence Handler for hold-phrase detection.
 */
export type ShortResponseCategory =
  | 'acknowledgement'
  | 'instruction'
  | 'question'
  | 'closing';

/**
 * Disruption types that can be introduced during a simulation session.
 * Trainers can configure 1-3 types per session.
 */
export type DisruptionType =
  | 'technical_term_confusion'
  | 'repeated_question'
  | 'misunderstanding'
  | 'interruption'
  | 'incomplete_data'
  | 'unclear_voice'
  | 'emotional_escalation';

/**
 * Annotation categories for replay annotations.
 * Used by the Replay Annotator to classify AI-generated and manual annotations.
 */
export type AnnotationCategory =
  | 'strength'
  | 'improvement_area'
  | 'critical_moment'
  | 'technique_used';

/**
 * Detected moment types for replay annotations.
 * Identifies specific conversational events worth highlighting.
 */
export type AnnotationMoment =
  | 'missed_empathy'
  | 'good_de_escalation'
  | 'long_pause'
  | 'interruption'
  | 'technique_usage';

// ---------------------------------------------------------------------------
// Shared Interfaces
// ---------------------------------------------------------------------------

/**
 * Language patterns generated by the Persona State Machine based on
 * persona type and current emotional intensity. Consumed by Fallback
 * Response Manager, Backchannel Controller, and Disruption Engine.
 */
export interface PersonaLanguagePatterns {
  toneMarkers: string[];
  preferredFillers: string[];
  responseLength: 'short' | 'medium' | 'long';
  interruptionLikelihood: number; // 0-1
}

/**
 * Records a single turn-taking evaluation event for post-session metrics.
 */
export interface TurnTakingEvent {
  timestampMs: number;
  silenceDurationMs: number;
  wasMultiClause: boolean;
  confidence: number; // 0-1
}

/**
 * Tracks a single disruption instance during a session.
 * Used by the Disruption Scenario Engine and persisted to
 * `telefun_history.disruption_results`.
 */
export interface DisruptionInstance {
  type: DisruptionType;
  triggeredAtExchange: number;
  resolved: boolean;
  attempts: number;
}

/**
 * Extended session metrics that include realistic mode data.
 * Extends the base SessionMetrics with turn-taking, fallback,
 * backchannel, persona, and disruption tracking.
 */
export interface SessionMetricsExtended extends SessionMetrics {
  turnTakingEvents: TurnTakingEvent[];
  fallbackCount: number;
  fallbackRecoveryCount: number;
  backchannelCount: number;
  personaIntensityHistory: PersonaIntensitySnapshot[];
  disruptionOutcomes: DisruptionInstance[];
  speakingDominanceRatio: number;
  estimatedWpm: number;
}

/**
 * Snapshot of persona emotional intensity at a given exchange.
 */
export interface PersonaIntensitySnapshot {
  exchangeIndex: number;
  intensity: number;
}

// ---------------------------------------------------------------------------
// Replay Annotator Types
// ---------------------------------------------------------------------------

/**
 * A single annotation on a conversation replay timeline.
 */
export interface ReplayAnnotation {
  id: string;
  timestampMs: number;
  category: AnnotationCategory;
  moment: AnnotationMoment;
  text: string;
  isManual: boolean;
  createdBy?: string; // user_id for manual annotations
}

/**
 * A coaching recommendation generated from session analysis.
 * Max 5 per session, each text limited to 200 characters.
 */
export interface CoachingRecommendation {
  text: string; // max 200 chars
  priority: number; // 1-5
}

/**
 * Result of replay annotation generation.
 */
export interface ReplayAnnotationResult {
  annotations: ReplayAnnotation[];
  summary: CoachingRecommendation[];
}

// ---------------------------------------------------------------------------
// Voice Dashboard Types
// ---------------------------------------------------------------------------

/**
 * Speaking speed classification based on WPM thresholds.
 */
export type SpeakingSpeedClassification = 'too_slow' | 'normal' | 'too_fast';

/**
 * Speaking dominance classification based on ratio thresholds.
 */
export type SpeakingDominanceClassification = 'dominated' | 'balanced' | 'passive';

/**
 * Post-session voice dashboard metrics computed from agent-only audio.
 */
export interface VoiceDashboardMetrics {
  speechClarity: number; // 0-10
  speakingSpeed: {
    wpm: number;
    classification: SpeakingSpeedClassification;
  };
  speakingDominance: {
    ratio: number; // 0-1
    classification: SpeakingDominanceClassification;
  };
  intonationVariability?: number; // 0-10, optional
}

// ---------------------------------------------------------------------------
// Persona Configuration (persisted to telefun_history.persona_config)
// ---------------------------------------------------------------------------

/**
 * Persona configuration stored per session.
 */
export interface PersonaConfig {
  personaType: ConsumerPersonaType;
  initialIntensity: number;
  finalIntensity: number;
}

// ---------------------------------------------------------------------------
// Re-exports for convenience
// ---------------------------------------------------------------------------

export type { TelefunSessionState };
